### ISSUE TITLE
Can not deploy report to the target org and it shows the following error message.

### ISSUE THREAD

**Issue by jakroll** [xjsender/haoide#101]
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.metadata in C:\Users\vicia hh wang\Desktop\Sublime Text Build UAT&PRD\Data\Installed Packages\haoide.sublime-package", line 518, in deploy
  File "salesforce.soap in C:\Users\vicia hh wang\Desktop\Sublime Text Build UAT&PRD\Data\Installed Packages\haoide.sublime-package", line 55, in create_request
  File "salesforce.soap in C:\Users\vicia hh wang\Desktop\Sublime Text Build UAT&PRD\Data\Installed Packages\haoide.sublime-package", line 217, in create_deploy_request
KeyError: 'testLevel'

**Comment by xjsender** [comment]
@jakroll , if you see this exception in the console, you must set your ``deploy_options`` before release 3.3.7, so you just need to remove the ``deploy_options`` from your ``User Settings``, it will be ok.

After release 3.3.7, I added a runSpeicifedTest feature which setting is kept in the ``deploy_options``, see more detail in issue #96 .
