### ISSUE TITLE
Request errors when saving classes

### ISSUE THREAD

**Issue by eugenevabishchevich** [xjsender/haoide#116]
Hey! Could you help me why I got these errors?
http://take.ms/VmqDS

**Comment by xjsender** [comment]
@eugenevabishchevich , it seems your network has problem, can you check whether there has any exception in the console.

**Comment by eugenevabishchevich** [comment]
Strange that I have this issue with one org only...

**Comment by xjsender** [comment]
@eugenevabishchevich , any exception in your sublime console?

**Comment by eugenevabishchevich** [comment]
Part of console code:
`reloading Packages/User/symbol_table.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/symbol_table.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/symbol_table.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
Exception in thread Thread-109:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.tooling in /Users/eugene/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 1024, in save_to_server
  File "salesforce.api.tooling in /Users/eugene/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 1079, in save_to_server
KeyError: 'State'

no command for selector: noop:
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
Exception in thread Thread-117:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.tooling in /Users/eugene/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 1073, in save_to_server
KeyError: 'State'

reloading Packages/User/symbol_table.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/symbol_table.sublime-settings
Exception in thread Thread-129:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.tooling in /Users/eugene/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 1079, in save_to_server
KeyError: 'State'

reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/component_metadata.sublime-settings
reloading Packages/User/symbol_table.sublime-settings
reloading Packages/User/component_metadata.sublime-settings`

**Comment by eugenevabishchevich** [comment]
Any ideas? I can't save any class.

**Comment by xjsender** [comment]
@eugenevabishchevich , what's your ``api_version`` setting?

**Comment by eugenevabishchevich** [comment]
Where I can check it?

**Comment by xjsender** [comment]
@eugenevabishchevich , you can check it at the most left of your sidebar.

**Comment by eugenevabishchevich** [comment]
@xjsender not sure that I understand where is it :(

**Comment by eugenevabishchevich** [comment]
@xjsender issue related to api_version. IDE has 36 as default and some sandboxes have 35 Spring.

**Comment by xjsender** [comment]
@eugenevabishchevich , wow, actually, I forgot to change it back to 35 and should't add it to commit as part of new release.

I will change it back to ``35``.

**Comment by Shababsoft** [comment]
@xjsender I believe spring'16 has API version 36.0 and all sandboxes and production orgs have already migrated to this API version.

**Comment by xjsender** [comment]
@Shababsoft ， I think I need to do investigate on the new version, there are many potential problem before update ``api_version`` to ``36``
