### ISSUE TITLE
'NoneType' object has no attribute 'items' when deploying

### ISSUE THREAD

**Issue by KMBorg** [xjsender/haoide#175]
When attempting to deploy Account.object to our production org, I receive the following error:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "main in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 1471, in run
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by aitiancai** [comment]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/Users/YanhaowWang/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package/main.py", line 1570, in run
AttributeError: 'NoneType' object has no attribute 'items'
