### ISSUE TITLE
An error in console

### ISSUE THREAD

**Issue by aitiancai** [xjsender/haoide#193]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\yanha\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_cleanup.py", line 81, in run
    os.remove(package_file)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\yanha\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\haoide.sublime-package'

**Comment by xjsender** [comment]
I recommend you to install green version.
