### ISSUE TITLE
View Code Coverage 

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#197]
API: 36

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "main in /Users/polzovatel/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 708, in run
  File "util in /Users/polzovatel/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 254, in view_coverage
  File "util in /Users/polzovatel/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 254, in <listcomp>
KeyError: 'line'

**Comment by xnamahx** [comment]
same here

**Comment by lushang** [comment]
The Salesforce Tooling API does not return expected response with code coverage information after run sync test now. Will use another approach to fix this issue.
