### ISSUE TITLE
Build v2.9.3 - not work at all after update

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#29]
no one function works - after plugin update. Please fix it, 

Thanks!

Debug log
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 176, in on_new
    callback.on_new(v)
  File "events in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 18, in on_new
  File "util in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 2328, in display_active_project
  File "context in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 168, in get_settings
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "events in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 44, in on_activated
  File "util in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 2328, in display_active_project
  File "context in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 168, in get_settings
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "events in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 44, in on_activated
  File "util in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 2328, in display_active_project
  File "context in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 168, in get_settings
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "events in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 44, in on_activated
  File "util in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 2328, in display_active_project
  File "context in /Users/maksimleshkevich/Library/Application Support/Sublime Text 3/Installed Packages/haoide.sublime-package", line 168, in get_settings
TypeError: 'NoneType' object is not iterable

**Comment by xjsender** [comment]
@maksimln , did you restart your sublime?

**Comment by maksimln** [comment]
yes, it is happens after restart

**Comment by xjsender** [comment]
@maksimln , what did you do? It seems your plugin upgrade is not succeed.

**Comment by xjsender** [comment]
@maksimln , how is going on?

**Comment by maksimln** [comment]
1. I saw that plugin update complete without any errors by opened Release note.
2. Close Sublime
3. Open Sublime
4. Try to active a project and Update project 
But all menu items is grayed out
http://take.ms/M8ko5

**Comment by maksimln** [comment]
Also it is happens not for me only

3 my friends have such problem

**Comment by eugene-vabishchevich** [comment]
I have this issue too. Can't update project http://take.ms/nE9lF

**Comment by xjsender** [comment]
@maksimln , you need to create new project firstly.

**Comment by xjsender** [comment]
Originally, you just need to have ``.config/session.json`` in the project path, since this version, another ``.config/metadata.json`` will be checked also, if one of these two cache files is not exist, you need to create new project before other commands are enabled.

**Comment by eugene-vabishchevich** [comment]
After click New Project I got this error:
Copyright © 2013-2015 By Hao Liu, Dev Channel, Build v2.9.3

[2015.05.11 12:46:17] [ERROR] INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session key: 00DJ0000003OqIr!AQwAQM6mWy_Dpst1xiO4E8uRQCgl9sLdB_CAOlqyJ5WIAxBsefNOIF8aibQpYmG1aFp7kht8cLqCEsarlMIcK_UQuur4hH__
This is expected, it can happen if the session has expired and swept away, or if the user logs out, or if its just someone trying to hack in.

**Comment by xjsender** [comment]
Can you just try to clear your session by ``HaoIDE > Session > Clear Session``, and then create new project again.

I seems another problem happened.

Please don't paste your confidential information to here.

**Comment by xjsender** [comment]
@maksimln , both,  if your issues are fixed, please close this issue, thanks.

BTW, if you think this plugin is helpful on your daily work, please star it, thanks.

**Comment by eugene-vabishchevich** [comment]
@xjsender 
I have tried HaoIDE > Cache > Clear Session Cache because I don't have Session menu item in HaoIDE menu. Session cleared but update project doesn't work.

When you plan to fix this issue?

**Comment by xjsender** [comment]
Can you try to create new project but not update project?

**Comment by eugene-vabishchevich** [comment]
Yea, it works. Thanks.

**Comment by maksimln** [comment]
Thanks

**Comment by xjsender** [comment]
Check  [this demo](https://github.com/xjsender/SublimeApexScreenshot/blob/master/BuildPackageXMLWithQuickPanel.gif) , you will be intresting on it.
