### ISSUE TITLE
Unable to retrieve / update some HaoIDE projects

### ISSUE THREAD

**Issue by eSh3m4** [xjsender/haoide#40]
Hi,
Hoide is raising the following exceptions whenever I try to create or update some projects linked to specific sandboxes whereas it works perfectly fine for the others (similar) sandboxes and work perfectly on MAC OSX. Thanks in advance for your help !

## Error log
*Running on WIN7 - Sublime Text v3083 - Haoide v3.0.0*

Exception in thread Thread-15:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.metadata in C:\......\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 71, in describe_metadata
  File "util in C:\...........\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 2181, in get_response_error
  File "util in C:\.........\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 2166, in getUniqueElementValueFromXmlString
  File "./xml/dom/minidom.py", line 1970, in parseString
  File "./xml/dom/expatbuilder.py", line 926, in parseString
  File "./xml/dom/expatbuilder.py", line 221, in parseString
xml.parsers.expat.ExpatError: syntax error: line 1, column 49

2015-06-04 11:27:56,352 Could not import subprocess32 module, falling back to subprocess module
reloading Packages/User/metadata.sublime-settings
Exception in thread Thread-16:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.metadata in C:\......\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 191, in retrieve
  File "salesforce.api.metadata in C:\......\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 307, in prepare_members
KeyError: 'metadata_objects_in_folder'

Traceback (most recent call last):
  File "processor in C:\......\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 1135, in <lambda>
  File "processor in C:\.......\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 1156, in handle_thread
KeyError: 'subscribed_metadata_folders'

**Comment by xjsender** [comment]
@eSh3m4 , can you try to execute ``HaoIDE > Metadata > Describe Metadata`` command in the main menu, check whether there has error message in the console?

**Comment by xjsender** [comment]
@eSh3m4 , this is a bug, exception for parsing error of ``describe_metadata`` is not caught.

I release a new version, you can get the error message when ``describe_metadata`` failed, can you upgrade your plugin and paste the error message of ``describe_metadata`` to here.

Thanks.

**Comment by eSh3m4** [comment]
Thanks @xjsender a lot :) 
The "Describe Metadata" command showed me a client side error due to proxy authentication with the given certificate. I solved the issue by using [CNTLM](http://cntlm.sourceforge.net/) to override the proxy

### Error log
*with HaoIde v3.0.0  - Console*
<urlopen error Tunnel connection failed: 407 Proxy Authentication Required>

*with HaoIde v3.0.1 - Error panel*
[ERROR] b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\n</p>\n</body></html>\n'
