### ISSUE TITLE
New classes and pages don't save to server.

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#92]
I just upgraded to v3.2.9, and as soon as the upgrade finished I restarted sublime and refreshed my project from the server.

I tried to create a new class in my project (haoide > new > apexclass), and the initial creation seems to work fine.  However, if i make any changes to the class, the changes are not saved to the server.  When I save to server, the console immediately says the save was successful:

![screenshot-01](https://cloud.githubusercontent.com/assets/4985056/13680486/8e7bbd12-e6ad-11e5-89be-1ee1090a92c2.PNG)

...but if I diff with the server, I can see that my changes weren't actually saved:

![screenshot-02](https://cloud.githubusercontent.com/assets/4985056/13680501/a280b952-e6ad-11e5-87e9-2babc4b52edb.PNG)

I experienced the same issue when creating a new page.

My current workaround is to do a complete project update after I've created my new classes/pages.  Once the entire project has been updated, I can save changes to the new classes.  I have to do this every time I add a new class/page.

**Comment by xjsender** [comment]
@reyesml , can you paste the console message to here, it seems there has exception thrown when you execute create operation.

**Comment by reyesml** [comment]
Here is the console message from sublime:

Exception in thread Thread-242:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.tooling in C:\Users\reyesm\Documents\SublimeText03\Sublime Text Build 3065 x64\Data\Installed Packages\haoide.sublime-package", line 981, in save_to_server
TypeError: 'NoneType' object is not subscriptable

**Comment by xjsender** [comment]
@reyesml , I already replicate this issue and fixed it, I will release the patch release today.

**Comment by reyesml** [comment]
@xjsender I upgraded to v3.3.1, and refreshed my project from the server.  I am now unable to save any changes to the server.  HaoIDE gives me the usual success message, but I get the following output from the sublimetext console:


Exception in thread Thread-50:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "salesforce.api.tooling in C:\Users\reyesm\Documents\SublimeText03\Sublime Text Build 3065 x64\Data\Installed Packages\haoide.sublime-package", line 980, in save_to_server
NameError: global name 'settings' is not defined

Traceback (most recent call last):
  File "processor in C:\Users\reyesm\Documents\SublimeText03\Sublime Text Build 3065 x64\Data\Installed Packages\haoide.sublime-package", line 1452, in <lambda>
  File "processor in C:\Users\reyesm\Documents\SublimeText03\Sublime Text Build 3065 x64\Data\Installed Packages\haoide.sublime-package", line 1507, in handle_thread
NameError: global name 'attributes' is not defined
